id: I115B5925
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T23:10:08+00:00'
last_modified: '2022-06-07T12:26:22.936544+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1623
  title: རྭ་བསྟོད་བསྡུས་གྲྭ།（སོག་ཧུ་རེའི་པར་མ）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D7E:
      image_group_id: I1KG1712
      title: ''
      total_pages: 430
      order: 1
      base_file: 4D7E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
