id: P000607
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1623
  title: རྭ་བསྟོད་བསྡུས་གྲྭ།（སོག་ཧུ་རེའི་པར་མ）
  author: ''
  volumes:
    ec00685c40824ef28945bcffce255203:
      image_group_id: I1KG1712
      title: ''
      volume_number: 1
      total_pages: 430
